//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HocPhi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienLai
    {
        public string MaBienLai { get; set; }
        public string MaHocSinh { get; set; }
        public string TongCong { get; set; }
        public string TinhTrang { get; set; }
        public string NgayNop { get; set; }
        public string NguoiNop { get; set; }
    
        public virtual HocSinh HocSinh { get; set; }
    }
}
